//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addTicket", ReplyAction="http://tempuri.org/IService1/addTicketResponse")]
        void addTicket(int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addTicket", ReplyAction="http://tempuri.org/IService1/addTicketResponse")]
        System.Threading.Tasks.Task addTicketAsync(int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/buyTickets", ReplyAction="http://tempuri.org/IService1/buyTicketsResponse")]
        int buyTickets(int num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/buyTickets", ReplyAction="http://tempuri.org/IService1/buyTicketsResponse")]
        System.Threading.Tasks.Task<int> buyTicketsAsync(int num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getRemainNum", ReplyAction="http://tempuri.org/IService1/getRemainNumResponse")]
        int getRemainNum();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getRemainNum", ReplyAction="http://tempuri.org/IService1/getRemainNumResponse")]
        System.Threading.Tasks.Task<int> getRemainNumAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WebDemo.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WebDemo.ServiceReference1.IService1>, WebDemo.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void addTicket(int count) {
            base.Channel.addTicket(count);
        }
        
        public System.Threading.Tasks.Task addTicketAsync(int count) {
            return base.Channel.addTicketAsync(count);
        }
        
        public int buyTickets(int num) {
            return base.Channel.buyTickets(num);
        }
        
        public System.Threading.Tasks.Task<int> buyTicketsAsync(int num) {
            return base.Channel.buyTicketsAsync(num);
        }
        
        public int getRemainNum() {
            return base.Channel.getRemainNum();
        }
        
        public System.Threading.Tasks.Task<int> getRemainNumAsync() {
            return base.Channel.getRemainNumAsync();
        }
    }
}
